-- 코드를 입력하세요
SELECT '/home/grep/src/' || BOARD_ID || '/' || FILE_ID ||FILE_NAME || FILE_EXT AS FILE_PATH
FROM USED_GOODS_FILE
WHERE BOARD_ID = (SELECT B.BOARD_ID
FROM (
SELECT A.*, RANK() OVER (ORDER BY A.VIEWS DESC) AS RANK
FROM USED_GOODS_BOARD A) B
WHERE RANK = 1)
ORDER BY FILE_ID DESC;